// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef MainGui_h
#define MainGui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Editor.H>

class MainGui {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *mainWindow;
  Fl_Input *input_path;
  Fl_Browser *browser_column_families;
  Fl_Browser *browser_keys;
  Fl_Text_Display *text_value_old;
  Fl_Light_Button *button_connect;
  Fl_Input *input_filter_column_families;
  Fl_Input *input_filter_keys;
  Fl_Button *add_column_family_button;
  Fl_Button *add_key_button;
  Fl_Button *save_content_button;
  Fl_Text_Editor *text_value;
  Fl_Button *del_column_family_button;
  Fl_Button *del_key_button;
};
#endif
