// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef Settings_h
#define Settings_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>

class SettingsDialog {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *Settings;
  Fl_Input *apiKey;
  Fl_Input *folder;
  Fl_Input *aria2Url;
  Fl_Choice *list;
  Fl_Button *Button_OK;
  Fl_Button *Button_Abbrechen;
  Fl_Choice *configs;
  Fl_Button *Button_load_config;
};
#endif
