// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "Settings.h"

Fl_Double_Window* SettingsDialog::make_window() {
  { Settings = new Fl_Double_Window(435, 346, "Settings");
    Settings->user_data((void*)(this));
    { apiKey = new Fl_Input(75, 68, 353, 38, "Api-Key");
    } // Fl_Input* apiKey
    { folder = new Fl_Input(75, 114, 353, 38, "Folder");
    } // Fl_Input* folder
    { aria2Url = new Fl_Input(75, 160, 353, 38, "Aria2-Url");
    } // Fl_Input* aria2Url
    { list = new Fl_Choice(75, 205, 353, 38, "List");
      list->down_box(FL_BORDER_BOX);
      list->add("TransferList");
      list->add("Folder");
    } // Fl_Choice* list
    { Button_OK = new Fl_Button(330, 307, 100, 28, "OK");
    } // Fl_Button* Button_OK
    { Button_Abbrechen = new Fl_Button(225, 307, 100, 28, "Abbrechen");
    } // Fl_Button* Button_Abbrechen
    { Fl_Box* o = new Fl_Box(0, 20, 294, 28, "Settings");
      o->labelsize(53);
    } // Fl_Box* o
    { configs = new Fl_Choice(75, 250, 240, 38, "Configs");
      configs->down_box(FL_BORDER_BOX);
    } // Fl_Choice* configs
    { Button_load_config = new Fl_Button(325, 255, 100, 28, "Load Config");
    } // Fl_Button* Button_load_config
    Settings->end();
  } // Fl_Double_Window* Settings
  return Settings;
}
