name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: MinSizeRel
  FLOW_ROOT: deps

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64

      - name: Build Boost
        id: boost
        uses: egor-tensin/build-boost@v1
        with:
          version: 1.78.0
          libraries: filesystem system
          platform: x64
          configuration: Release

      - name: Show paths
        run: |
          printf 'Boost has been unpacked to: %s\n' '${{ steps.boost.outputs.root }}'
          printf 'Libraries can be found here: %s\n' '${{ steps.boost.outputs.librarydir }}'
        shell: bash

      - name: Get Dependencies
        run: sudo apt-get install librocksdb-dev liblz4-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev libzstd-dev libfltk1.3-dev

      - name: Get Reps
        run: mkdir ${{env.FLOW_ROOT}} && cd ${{env.FLOW_ROOT}} && git clone https://github.com/Accessory/FlowUtils.git && git clone https://github.com/Accessory/FlowDatabase.git

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D "BOOST_ROOT=${{ steps.boost.outputs.root }}" -D "BOOST_LIBRARYDIR=${{ steps.boost.outputs.librarydir }}" \

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
